### ISSUE TITLE
New firware doesnt work with tool

### ISSUE THREAD

**Issue by joeg1484** [hjma29/ovcli#4]
I sent an e-mail a while ago but wanted to raise a bug.

For some reason, when I try to view connections, I am not able to get a list of devices or the mac address. 

-----------------------------------------
We are wanting to use your cli application to get mac addresses from our systems with profiles. When I run the command:

ovcli.exe show serverprofile --name "R1F1B1-Test-WithNetwork-vlan203"

for one of our systems, all we get is this:

Name:                 R1F1B1-Test-WithNetwork-vlan203
Description:
ProfileTemplate:      cee_workstation_template-vlan203
TemplateCompliance:   Compliant
ServerHardware:       Rack1 Frame1 7QD, bay 1
ServerPower:          Off
ServerHardwareType:   SY 480 Gen10 1

Connections
ID   Name   Network   VLAN   MAC   Port   Interconnect   Boot

OS Deployment Setting

We do not see the connections. However, in the OV GUI, we see all the info:

-----------------------------------------

Reply from e-mail

Hi Joe,
 
The tool used to work with OneView 4.0 but it seems 4.10 has some API change so it doesn’t work any more.
 
I have to go back into the code to see what’s the problem but currently I’m working on other projects and won’t have time in short term. I will keep this in mind and give you an update when I fix the problem.
 
Hongjun

**Comment by hjma29** [comment]
I got some time to dig into code today and found the issue. The root problem was new OneView 4.10 changed the server profile connection data structure. I modified the code so it can work with the 4.10 now.
